name: Keep my Duolingo streak

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
    inputs: {}

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Random delay (up to 1 hour)
        if: github.event_name == 'schedule'
        run: sleep $((RANDOM % 3600))
      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 5
  delete-old-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 10
          retain_days: 30
